### ISSUE TITLE
Support for 2021

### ISSUE THREAD

**Issue by misspent** [gurinderhans/not-interested#3]
This is essential at this point, thanks to the bs YouTube keeps throwing at you. Any verdict on if you'll ever touch this project again?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
+1
This project is really useful!

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I created a Tampermonkey script for this task.
https://github.com/0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video

**Comment by szebrowski** [comment]
super cool, thanks! :)

**Comment by gurinderhans** [comment]
Thanks! And updated since I found myself needing this again :)
